server:
  port: ${DEV_PORT}

spring:
  application:
    name: inspriation

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/inspiration?autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: 6379

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: yeonggamt@gmail.com
    password: ktmygrzezaeyfnvv
    auth-mail: ${AUTH_MAIL}
    auth-token: ${AUTH_TOKEN}

  jwt:
    secret: ${SECRET_KEY}

logging:
  level:
    root: info
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
