server:
  port: ${LOCAL_PORT}

spring:

  application:
    name: inspriation

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/inspiration?autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    sign-up-email-send-mail: ${SIGN_UP_EMAIL_SEND_MAIL}
    update-password-email-send-mail: ${UPDATE_PASSWORD_EMAIL_SEND_MAIL}
    auth-token: ${AUTH_TOKEN}

  jwt:
    secret: ${SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

#  pattern:
#    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

