server:
  port: ${LOCAL_PORT}

spring:
  application:
    name: inspriation

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/inspiration?autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    format_sql: true

  jwt:
    header: Authorization
    secret: cg3FinueMfHj7ouyOq5MhPF7Xz2XTBxAq0LPm8yi1HKFhz8vqPH0_DwSVPAenc1kFDWgRKdrUq4FUDWbm_KNAg # ${SECRET_KEY}
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 86400


#logging:
#  level:
#    root: debug
#  pattern:
#    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
